// ============================================================================
// /api/config.js — Vercel serverless function
// ============================================================================
// Возвращает JavaScript-файл, который устанавливает window.DASHBOARD_CONFIG.
// Реальные значения вебхуков берутся из env-переменных Vercel — НЕ из кода.
//
// Маршрутизация:
//   vercel.json переписывает запрос /config.js → /api/config
//   Поэтому в браузере <script src="config.js"> загружает этот файл.
//
// Локальная разработка:
//   - Этот файл не используется. Локально разработчик создаёт статический
//     config.js из шаблона config.example.js (см. README.md).
// ============================================================================

module.exports = (req, res) => {
  // Никогда не кэшировать — иначе при ротации вебхуков пользователи
  // будут получать устаревший конфиг из CDN
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0');
  res.setHeader('Pragma', 'no-cache');
  res.setHeader('Expires', '0');
  res.setHeader('Content-Type', 'application/javascript; charset=utf-8');

  const config = {
    // Дакар (CRM)
    BITRIX_DAKAR_WEBHOOK_URL: process.env.BITRIX_DAKAR_WEBHOOK_URL || '',
    BITRIX_DAKAR_ENTITY_TYPE_ID: parseInt(process.env.BITRIX_DAKAR_ENTITY_TYPE_ID || '129', 10),
    BITRIX_DAKAR_TASK_URL_PREFIX: process.env.BITRIX_DAKAR_TASK_URL_PREFIX || 'https://dakar.bitrix24.ru/crm/type/129/details/',

    // АтиЛаб / Внедрение (Tasks + IM + Disk)
    BITRIX_ATILAB_WEBHOOK_URL: process.env.BITRIX_ATILAB_WEBHOOK_URL || '',
    BITRIX_ATILAB_TASK_URL: process.env.BITRIX_ATILAB_TASK_URL || '',

    // Чат ВНЕДРЕНИЯ
    BITRIX_VNEDRENIE_CHAT_DIALOG_ID: process.env.BITRIX_VNEDRENIE_CHAT_DIALOG_ID || 'chat7568'
  };

  // Проверяем, что обязательные переменные заданы
  const missing = [];
  if (!config.BITRIX_DAKAR_WEBHOOK_URL) missing.push('BITRIX_DAKAR_WEBHOOK_URL');
  if (!config.BITRIX_ATILAB_WEBHOOK_URL) missing.push('BITRIX_ATILAB_WEBHOOK_URL');
  if (missing.length > 0) {
    console.error('[api/config] Missing env vars:', missing.join(', '));
  }

  // Возвращаем как JavaScript-код, который устанавливает window.DASHBOARD_CONFIG
  const js = `// Auto-generated by /api/config from Vercel env vars
// DO NOT EDIT — changes should be made in Vercel project settings → Environment Variables
window.DASHBOARD_CONFIG = ${JSON.stringify(config, null, 2)};`;

  res.status(200).send(js);
};
